version: '2.1'

networks:
  irn_test_net:
    ipam:
      driver: default
      config:
        - subnet: 172.40.1.0/24

services:
  node_0:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./irn -n dev-1
    networks:
      irn_test_net:
        ipv4_address: 172.40.1.2

  node_1_rpc:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./irn -n dev-1 --peer 172.40.1.2:44668 --rpc 8080 -v
    depends_on:
      node_0:
        condition: service_started
    networks:
      irn_test_net:
    ports:
      - "8080:8080"

  node_2_rpc:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./irn -n dev-1 --peer 172.40.1.2:44668 --rpc 8080
    depends_on:
      node_0:
        condition: service_started
    networks:
      irn_test_net:
    ports:
      - "8081:8080"

  node_logger:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./irn -n dev-1 --peer 172.40.1.2:44668 -v
    depends_on:
      node_0:
        condition: service_started
    networks:
      irn_test_net:

  node_n:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./irn -n dev-1 --peer 172.40.1.2:44668
    depends_on:
      node_0:
        condition: service_started
    networks:
      irn_test_net:
